Nettbutikk/Nettbutikk/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nettbutikk.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult About()
        {
            return View();
        }
    }
}

Nettbutikk/Nettbutikk/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nettbutikk.Models;
using System.Diagnostics;

namespace Nettbutikk.Controllers
{
    public class CustomerController : Controller
    {
        
        
        public ActionResult Register()
        {
            return View();

        }

        //Her kommer man dersom man har registrert en ny bruker 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Customer newUser, String password_confirmation)
        {
            if (ModelState.IsValid)
            {
                if (!newUser.password.Equals(password_confirmation))
                {
                    ViewBag.confirmation = true;
                    return View();
                }
                var customerDB = new DBCustomer();

                if (!customerDB.checkEmail(newUser.email,null))
                {
                    ViewBag.email = true;
                    return View();
                }
                else
                {

                    byte[] hashedPassword = makeHash(newUser.password);
                    bool insertOK = customerDB.add(newUser, hashedPassword);
                    if (insertOK)
                    {
                        logInUser(newUser.email);
                        return RedirectToAction("PersonalSite");
                    }
                }
            }
            return View();
        }

        public ActionResult LogOut()
        {
            DBOrder order = new DBOrder();
            List<Product> topFive = order.getMostSold();
            Session["loggedInUser"] = null;
            return RedirectToAction("Frontpage","Main",topFive);

        }
        

        // Her skjekker kaller man først opp userExits, dersom den gjør det så er man logget inn
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(String un, String pw)
        {
    
            var customerDB = new DBCustomer(); 
            var hashedPassword = makeHash(pw); 
            if (customerDB.validate(un, hashedPassword))
            {
                logInUser(un);
                return Json(true);
            }
            else
            {
                Session["loggedInUser"] = null;
                return Json(false);
            }

        }

        //Dersom man går inn i den personlige siden så viser man denne siden, ellers må man logge inn.
        public ActionResult PersonalSite()
        {
            if (Session["loggedInUser"] != null )
            {
                TempData["pview"] = "none";
                Customer c = (Customer)Session["loggedInUser"];
                return View("PersonalSite",c);
           }
            return RedirectToAction("Frontpage","Main");
        }

        //Hasher passordet
        private static byte[] makeHash(string inPassword)
        {
            byte[] inData, outData;
            var algorithm = System.Security.Cryptography.SHA256.Create();
            inData = System.Text.Encoding.ASCII.GetBytes(inPassword);
            outData = algorithm.ComputeHash(inData);
            return outData;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult updateUserPassword(String op, String np, String bp)
        {
            if(Session["loggedInUser"]==null)
                return RedirectToAction("Frontpage", "Home");
            if (ModelState.IsValid)
            {
                Customer c = (Customer)Session["loggedInUser"];
                byte[] hpass = makeHash(op);
                if (Enumerable.SequenceEqual(c.hashpassword, hpass))
                {
                    if (np.Equals(bp))
                    {
                        byte[] hashedPassword = makeHash(np);
                        c.hashpassword = hashedPassword;

                        var customerDB = new DBCustomer();
                        bool updateOK = customerDB.updatePw(c.id, hashedPassword);

                        if (updateOK)
                        {
                            Session["loggedInUser"] = c;
                            TempData["changed"] = "Passord ble endret";
                            return RedirectToAction("PersonalSite");
                        }
                        else
                        {
                            ViewBag.correct = "klarte ikke oppdatere";
                            
                            return View();
                        }
                    } ViewBag.correct = "bekreftet ikke passordet riktig";
                    return View();
                } ViewBag.correct = "ikke riktig nåværende passord";
                return View();
            } return RedirectToAction("PersonalSite");
        }

        public ActionResult updateUserPassword()
        {

            Customer c = (Customer)Session["loggedInUser"];
            if (c == null)
                return RedirectToAction("Frontpage", "Home");
            TempData["pview"] = "password";
            return View("PersonalSite",c);
        }

        public ActionResult updateUserinfo()
        {
            Customer c = (Customer)Session["loggedInUser"];
            if (c == null)
                return RedirectToAction("Frontpage", "Home");
            TempData["pview"] = "info";
            return View("PersonalSite",c);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult updateUserinfo(Customer newUser)
        {

            if (ModelState.IsValid)
            {
                Customer c = (Customer)Session["loggedInUser"];
                var customerDB = new DBCustomer(); 
                if (!customerDB.checkEmail(newUser.email,c.id))
                {
                    ViewBag.ok = "email er i bruk av annen bruker, velg en annen";
                    return View();
                }
       
                  c.firstname = newUser.firstname;
                  c.lastname = newUser.lastname;
                  c.email = newUser.email;
                  c.phonenumber = newUser.phonenumber;
                  c.address = newUser.address;
                  c.postalcode = newUser.postalcode;
                  c.postalarea = newUser.postalarea;
                  
                    bool updateOK = customerDB.update(c.id, c);
                
                    if (updateOK)
                    {
                        Session["loggedInUser"] = c;
                        TempData["changed"] = "Brukerinformasjon ble oppdatert";
                        return RedirectToAction("PersonalSite"); 
                    }
                    else
                    {
                       Customer old = (Customer)Session["loggedInUser"];
                       ViewBag.ok = "klarte ikke oppdatere"; 
                       return View();
                    }
            }
            ViewBag.ok = "et felt er blankt, fyll det ut og trykk oppdater";
            return View();
        }

        public ActionResult viewOrderHistory()
        {
            var user = (Customer) Session["LoggedInUser"];
            if (user == null)
                return RedirectToAction("Frontpage", "Home");
            var db = new DBOrder();
            List<Order> list = db.getOrders(user.id);
            TempData["pview"] = "orderline";
            TempData["list"] = list;
            return View("PersonalSite", user);
        }

        private void logInUser(String un)
        {
            var customerDB = new DBCustomer(); 
            var founduser = customerDB.findCustomer(un);
            
            if(int.Parse(founduser.postalcode) < 1000)
            {
                founduser.postalcode = "0" + founduser.postalcode;
                if (int.Parse(founduser.postalcode) < 100)
                {
                    founduser.postalcode = "0" + founduser.postalcode;
                    if(int.Parse(founduser.postalcode) < 10)
                        founduser.postalcode = "0" + founduser.postalcode;
                }

            }

            founduser.shoppingcart = new ShoppingCart(founduser.id);
            Session["loggedInUser"] = founduser;
            
        }

    }
}

Nettbutikk/Nettbutikk/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nettbutikk.Models;
using System.Diagnostics;

namespace Nettbutikk.Controllers
{
    public class ProductController : Controller
    {

        public ActionResult ListProducts(int? id, string sc, int? sort)
        {
            var db = new DBProduct();
            List<Product> listOfProducts;
            if(sc != null && sc.Equals("yes"))
              {
                listOfProducts = db.getAll(id,sc,sort);
              }
            else
             {
                
                listOfProducts = db.getAll(id,sort);
             }
            
            return View(listOfProducts);
        }


        public ActionResult Search(string searchString)
        {
            var db = new DBProduct();
            List<Product> listOfProducts;
            
            if(!String.IsNullOrEmpty(searchString))
            {
                listOfProducts = db.getResult(searchString);
                return View(listOfProducts);
            }
            else
            {
                listOfProducts = db.getResult("Tomt");
                return View(listOfProducts);
            }
        }

        public ActionResult viewProduct(int id)
        {
            var db = new DBProduct();
            Product p = db.get(id);
            return View(p);
        }

        public JsonResult getResults(string term)
        {
            var db = new DBProduct();
            List<string> foundProducts = db.getAutoComplete(term);

            return Json(foundProducts, JsonRequestBehavior.AllowGet);
        }
    }
}

Nettbutikk/Nettbutikk/Controllers/ShoppingCartController.cs
using Nettbutikk.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nettbutikk.Controllers
{
    public class ShoppingCartController : Controller
    {
        public ActionResult viewShoppingCart()
        {
            ShoppingCart cart = getCart();
            if (cart != null)
                return View(cart);
            else
                return RedirectToAction("Frontpage", "Main");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addToCart(int quantity, int itemnumber)
        {
            var db = new DBProduct();
            Product p = db.get(itemnumber);
            ShoppingCart cart = getCart();
            if (cart == null)
                return Json(false);  
            ShoppingCartItem item = new ShoppingCartItem(p, quantity);
            List<ShoppingCartItem> list = cart.shoppingCartItems;
            cart.sum += p.price * quantity;
            list.Add(item);

            return RedirectToAction("viewShoppingCart");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult updateCart(int id, int quantity)
        {
            Customer cust = (Customer)Session["LoggedInUser"];
            ShoppingCart cart = cust.shoppingcart;
            cart.sum -= cart.shoppingCartItems[id].price;
            cart.shoppingCartItems[id].price = cart.shoppingCartItems[id].product.price * Math.Abs(quantity);
            cart.shoppingCartItems[id].quantity = Math.Abs(quantity);

            cart.sum += cart.shoppingCartItems[id].price;
            Session["LoggedInUser"] = cust;
            return RedirectToAction("viewShoppingCart");
        }

        public ActionResult removeItem(int id)
        {
            Customer cust = (Customer)Session["LoggedInUser"];
            ShoppingCart cart = cust.shoppingcart;
            cart.sum -= cart.shoppingCartItems[id].price; 
            cart.shoppingCartItems.RemoveAt(id);
            Session["LoggedInUser"] = cust;
            return RedirectToAction("viewShoppingCart");
        }
 
        private ShoppingCart getCart()
        {
            if (Session["loggedInUser"] != null)
            {
                Customer c = (Customer)Session["loggedInUser"];
                ShoppingCart cart = c.shoppingcart;
                return cart;
            }
            return null;
        }


        public ActionResult checkout(Order order)
        {
            RedirectToAction("viewShoppingCart");
            if (order.id != 0)
            {
                return View(showOrder(order));
            }
                
            
            ViewBag.Empty = false; 
            ShoppingCart cart = getCart();
            if (cart == null)
            {
                ViewBag.Empty = true;
                return View();
            }

            var orderDB = new DBOrder();
            var OrderId = orderDB.checkout(cart);
            
            var returnCustomer= (Customer) Session["LoggedInUser"];
            returnCustomer.shoppingcart = new ShoppingCart(returnCustomer.id);
            Session["LoggedInUser"] = returnCustomer; 

            return View(new BillingDocument()
            {
                customer = returnCustomer,
                shoppingcart = cart,
                order = new Order()
                {
                    id = OrderId,
                    customerid = returnCustomer.id,
                    orderdate = DateTime.Now
                },
                sum = cart.sum, 
                exmva = cart.sum * 0.8,
                mva = cart.sum * 0.2
            }); 

        }

        private BillingDocument showOrder(Order id)
        {
  
            var orderDB = new DBOrder();
            List<OrderLine> list = orderDB.getOrder(id.id);
            List<ShoppingCartItem> cartItems = new List<ShoppingCartItem>();
            var cartSum = 0;
            foreach(var item in list){
                cartItems.Add(new ShoppingCartItem(item.product, item.quantity));
                cartSum += item.product.price * item.quantity;
            };
            var cart = new ShoppingCart(id.customerid)
            {
                shoppingCartItems = cartItems,
                sum = cartSum
            };
            var billingDoc = new BillingDocument(){
                order = id,
                customer = (Customer) Session["LoggedInUser"],
                shoppingcart = cart,
                sum = cart.sum, 
                exmva = cart.sum * 0.8,
                mva = cart.sum * 0.2

            };
            return billingDoc;
        }
    }
}

Nettbutikk/Nettbutikk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" href="~/Content/img/logo/snublevann_liten_mork.ico">
    <title>Snublevann.no</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link href="~/Content/Custom/customNav.css" rel="stylesheet" /> 
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Custom/MainSheet.css" rel="stylesheet" />
    <link href="~/Content/Custom/SideMenu.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-latest.min.js"
            type="text/javascript"></script>
    <script src="~/Scripts/Custom/Collapse.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/jquery-ui.theme.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.structure.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.structure.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <link href="~/Content/notify.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-notify.min.js"></script>
    <script src="~/Scripts/Custom/Login.js"></script>
    <script src="~/Scripts/Custom/ProductListing.js"></script>
    <!--workaround for urler på server, da url.action ikke fungerer i js-filer, og hardkoding er ikke et alternativ siden siten publiseres på dotnetserver-->
    <script type="text/javascript">
        var viewproduct = '@Url.Action("viewProduct", "Product", new { id = "__id__" })';
        var addtocart = '@Url.Action("addToCart","ShoppingCart")';
    </script>
    <script type="text/javascript">
        $(function () {
            $("#txtSearch").autocomplete({
                source: '@Url.Action("getResults", "Product")',
                minLength: 1,
                select: function(event, ui)
                {
                    $("#txtSearch").submit();
                }
            });
        });
    </script>



</head>
<body>
    <div class="container">
            <div class="navbar navbar-inner" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>          
                </div>
                <div class="row">
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <a href="~/Main/Frontpage" id="homeLink"><img src="~/Content/img/logo/snublevann_light_transparent.png" id="logo" width="500" height="96" style="margin-top: 20px; margin-left: 20px" /></a> 
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <div class="navUl pull-right">
                                        @if (Session["loggedInUser"] == null)
                                        {
                                            <a href="@Url.Action("Register", "Customer")">
                                                <i class="glyphicon glyphicon-pencil"> </i> Registrer
                                            </a>
                                            <a href="#LoginModal" id="loginBtn" data-login="true" data-toggle="modal"><i class="glyphicon glyphicon-log-in"> </i> Logg Inn</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("viewShoppingCart", "ShoppingCart")">
                                                <i class="glyphicon glyphicon-shopping-cart"> </i> Handlekurv
                                            </a>
                                            
                                            <a href="@Url.Action("PersonalSite", "Customer")">
                                                <i class="glyphicon glyphicon-user"> </i> MinSide
                                            </a>
                                            
                                            <a href="@Url.Action("LogOut", "Customer")">
                                                <i class="glyphicon glyphicon-log-out"> </i> Logg ut
                                            </a>
                                        }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-2">
                <div class="panel panel-default pull-left" style="position:absolute; margin-top:0px; background:#180d00; border: 0">
                    <div class="panel-body">
                        <div class="pull-left">
                            <div id="menu_container">
                                <div id="accordion">
                                        @using (Html.BeginForm("Search", "Product", FormMethod.Get, new { @class = "form-inline", @role = "form", @style = "margin-top:0px; padding-bottom:12px" }))
                                    {
                                        <div class="row">
                                            <div class="col-sm-9 col-md-9" style="padding-right:0px">
                                                <div class="form-group">
                                                    <div class="input-group">

                                                        @Html.TextBox("searchString", null, new { id = "txtSearch", @class = "form-control", @style = "margin-top:12px; background-color: #dfc8ab; border-color:#a5862c ", placeholder = "Søk etter vare" })
                                                    </div>
                                                    </div>
                                                </div>
                                            <div class="input-group-btn pull-left">
                                                <button class="btn btn-success" type="submit" style="background-color:#a5862c; width: 35px; border-color:#a5862c">
                                                    <span class="glyphicon glyphicon-search"></span>
                                                </button>
                                            </div>
                                        </div>
                                    }
                                    <h4>Kategori</h4>
                                    <div class="item" id="Subcategory">
                                        <a class="sub">Øl</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 1, sc = "no" })'> Alle</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 1, sc = "yes"})'>Overgjæret</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 2, sc = "yes" })'>Undergjæret</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 3 , sc = "yes"})'>Spontangjæret</a>
                                    </div>
                                </div>
                                <div id="accordion">
                                    <div class="item" id="Subcategory">
                                        <a class="sub">Rødvin</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 2, sc = "no" })'> Alle</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 4, sc = "yes" })'>Fyldig</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 5, sc = "yes" })'>Mild</a>
                                    </div>
                                </div>
                                <div id="accordion">
                                    <div class="item" id="Subcategory">
                                        <a class="sub">Hvitvin</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 3, sc = "no" })'> Alle</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 7, sc = "yes" })'>Tørr</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 6, sc = "yes" })'>Søt</a>
                                    </div>
                                </div>
                                <div id="accordion">
                                    <div class="item" id="Subcategory">
                                        <a class="sub">Brennevin</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 4 , sc = "no"})'> Alle</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 8, sc = "yes" })'>Vodka</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 9, sc = "yes" })'>Rom</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 11, sc = "yes" })'>Cognac</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 12, sc = "yes" })'>Wiskey</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 10, sc = "yes" })'>Likør</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 13, sc = "yes" })'>Likør over 22%</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 14, sc = "yes" })'>Akevitt</a>
                                    </div>
                                </div>
                                <div id="accordion">
                                    <div class="item" id="Subcategory">
                                        <a class="sub">Musserende</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 5, sc= "no" })'> Alle</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 15, sc= "yes" })'>Champagne</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 16, sc= "yes" })'>Cava</a>
                                        <a href='@Url.Action("ListProducts", "Product", new { id = 17, sc= "yes" })'>Prosecco</a>
                                    </div>
                                </div>
                                <br />
                                <br />
                                <br />
                                <div id="accordion">
                                    <div class="item" id="Subcategory">
                                        @Html.ActionLink("Om oss", "About", "About")
                                    </div>
                                    </div>
                                
                
                                </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-10">
                            
                @RenderBody()
                           
                            <div class="row">
                                <div class="footer">
                                    <div class="jumbotron footerjumbo">
                                         Copyright &copy; @DateTime.Now.Year Snublevann - All rights reserved.
                                    </div>
            </div>
        </div>
        </div>
                    </div>
            </div>
        <div class="space" style="width:100%; height:10px">

    </div>

    @Html.Partial("~/Views/Customer/LoginModal.cshtml")
    @Html.Partial("~/Views/Customer/NotLoggedInModal.cshtml")
</body>

</html>